# Generated by Django 4.1 on 2023-10-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_store_min_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
    ]
