# Generated by Django 4.1 on 2023-10-13 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_category_img_path_category_url_store_avg_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_soldout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='thumbnail_path',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='thumbnail_path',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('discount', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_set', to='board.menu')),
            ],
        ),
    ]
