# Generated by Django 4.1 on 2023-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_menu_is_soldout_alter_menu_thumbnail_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_info',
            old_name='coupon',
            new_name='add_dc',
        ),
        migrations.RemoveField(
            model_name='store',
            name='min_delivery',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='delivery_info',
            name='prom',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_info',
            name='prom_cond',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
