# Generated by Django 4.1 on 2023-10-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_coupon_delivery_info_add_dc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='menu',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
