# Generated by Django 4.1 on 2023-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_menu_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='menu',
            field=models.TextField(null=True),
        ),
    ]
