# Generated by Django 4.1 on 2023-10-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_alter_review_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_info',
            old_name='add_dc',
            new_name='fee_list',
        ),
        migrations.AddField(
            model_name='delivery_info',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
